import { db } from './db';
import { content } from '@shared/schema';

// Auto-generated seed file - Last updated: 2025-08-06T03:48:22.267Z
// Total items: 36
const realContent = [
  {
    "id": "928a1501-97dd-427c-b93b-157d9821a14c",
    "title": "Stranger Things",
    "description": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    "type": "show",
    "genre": "sci-fi",
    "service": "netflix",
    "serviceContentId": "80057281",
    "directUrl": "https://www.netflix.com/title/80057281",
    "imageUrl": "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    "rating": "TV-14",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 51,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.219Z",
    "updatedAt": "2025-08-06T03:40:19.219Z"
  },
  {
    "id": "db02bbc6-2190-4d05-b6ea-bc18cdaa6b8c",
    "title": "Wednesday",
    "description": "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    "type": "show",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "81231974",
    "directUrl": "https://www.netflix.com/title/81231974",
    "imageUrl": "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    "rating": "TV-14",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 45,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.326Z",
    "updatedAt": "2025-08-06T03:40:19.326Z"
  },
  {
    "id": "3bd2b46e-1ea5-4363-8af9-43d7aef2040b",
    "title": "Squid Game",
    "description": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    "type": "show",
    "genre": "thriller",
    "service": "netflix",
    "serviceContentId": "81040344",
    "directUrl": "https://www.netflix.com/title/81040344",
    "imageUrl": "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    "rating": "TV-MA",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.430Z",
    "updatedAt": "2025-08-06T03:40:19.430Z"
  },
  {
    "id": "933389b6-646e-4128-9de4-fd88c232f0f3",
    "title": "The Crown",
    "description": "This drama follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    "type": "show",
    "genre": "drama",
    "service": "netflix",
    "serviceContentId": "80025678",
    "directUrl": "https://www.netflix.com/title/80025678",
    "imageUrl": "https://image.tmdb.org/t/p/w500/4g5gK5eGWZg8swIZl6eX2AoJp8S.jpg",
    "rating": "TV-MA",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.533Z",
    "updatedAt": "2025-08-06T03:40:19.533Z"
  },
  {
    "id": "1ae785d8-068b-477a-9709-a20e242bc65b",
    "title": "Ozark",
    "description": "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.",
    "type": "show",
    "genre": "crime",
    "service": "netflix",
    "serviceContentId": "80117552",
    "directUrl": "https://www.netflix.com/watch/80117552",
    "imageUrl": "https://image.tmdb.org/t/p/w500/m73QjSFgKQ05OKyZbIJqYklAc4G.jpg",
    "rating": "TV-MA",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.639Z",
    "updatedAt": "2025-08-06T03:40:19.639Z"
  },
  {
    "id": "b34776ab-fee7-4da6-a66c-5e5c43c9c1b5",
    "title": "Dark",
    "description": "A missing child causes four families to help each other for answers. What they discover is something far more mysterious than they ever imagined.",
    "type": "show",
    "genre": "sci-fi",
    "service": "netflix",
    "serviceContentId": "80100172",
    "directUrl": "https://www.netflix.com/title/80100172",
    "imageUrl": "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg",
    "rating": "TV-MA",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.744Z",
    "updatedAt": "2025-08-06T03:40:19.744Z"
  },
  {
    "id": "f3dbf649-8fc5-4c41-ab7b-d664fa1ba7f0",
    "title": "Red Notice",
    "description": "An FBI profiler pursuing the world's most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who's always one step ahead.",
    "type": "movie",
    "genre": "action",
    "service": "netflix",
    "serviceContentId": "81161626",
    "directUrl": "https://www.netflix.com/title/81161626",
    "imageUrl": "https://image.tmdb.org/t/p/w500/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 118,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.847Z",
    "updatedAt": "2025-08-06T03:40:19.847Z"
  },
  {
    "id": "9d5907f1-329b-4f48-96eb-4314b6fa7def",
    "title": "Glass Onion: A Knives Out Mystery",
    "description": "Detective Benoit Blanc travels to Greece to peel back the layers of a mystery involving a new cast of colorful suspects.",
    "type": "movie",
    "genre": "mystery",
    "service": "netflix",
    "serviceContentId": "81458416",
    "directUrl": "https://www.netflix.com/watch/81458416",
    "imageUrl": "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 139,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.951Z",
    "updatedAt": "2025-08-06T03:40:19.951Z"
  },
  {
    "id": "457d714f-468d-4886-af83-b441ac439631",
    "title": "The Boys",
    "description": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    "type": "show",
    "genre": "action",
    "service": "amazon-prime",
    "serviceContentId": "B0875JNV76",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b0875jnv76",
    "imageUrl": "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg",
    "rating": "TV-MA",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.054Z",
    "updatedAt": "2025-08-06T03:40:20.054Z"
  },
  {
    "id": "36848caa-1dd7-4526-9c3c-e89d230674a1",
    "title": "The Marvelous Mrs. Maisel",
    "description": "A housewife in 1958 decides to become a stand-up comic.",
    "type": "show",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B077RMZL8J",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b077rmzl8j",
    "imageUrl": "https://image.tmdb.org/t/p/w500/zS7fQiOZiKCVH2vlYSiIsFWW8hh.jpg",
    "rating": "TV-14",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 50,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.158Z",
    "updatedAt": "2025-08-06T03:40:20.158Z"
  },
  {
    "id": "94162723-3dc9-414f-8265-b45569a80941",
    "title": "Tom Clancy's Jack Ryan",
    "description": "An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment as he uncovers a pattern in terrorist communication.",
    "type": "show",
    "genre": "thriller",
    "service": "amazon-prime",
    "serviceContentId": "B07GC2KLBY",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b07gc2klby",
    "imageUrl": "https://image.tmdb.org/t/p/w500/q7HidVGjVSdJOlGcnr7tjjW2eLq.jpg",
    "rating": "TV-14",
    "year": 2018,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.261Z",
    "updatedAt": "2025-08-06T03:40:20.261Z"
  },
  {
    "id": "e9500b82-b38a-469a-a97c-bb23370dea34",
    "title": "The Lord of the Rings: The Rings of Power",
    "description": "Epic drama set thousands of years before the events of J.R.R. Tolkien's The Hobbit and The Lord of the Rings follows an ensemble cast of characters.",
    "type": "show",
    "genre": "fantasy",
    "service": "amazon-prime",
    "serviceContentId": "B0B5SV1RTM",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b0b5sv1rtm",
    "imageUrl": "https://image.tmdb.org/t/p/w500/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    "rating": "TV-14",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 70,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.364Z",
    "updatedAt": "2025-08-06T03:40:20.364Z"
  },
  {
    "id": "7fbba768-cf84-4d58-9892-dd2eb5f8b8a0",
    "title": "Invincible",
    "description": "Teen Mark Grayson inherits his father's superpowers and learns that his legendary dad may not be who he thought he was.",
    "type": "show",
    "genre": "animation",
    "service": "amazon-prime",
    "serviceContentId": "B00BQJMRWI",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b00bqjmrwi",
    "imageUrl": "https://image.tmdb.org/t/p/w500/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg",
    "rating": "TV-MA",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 45,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.467Z",
    "updatedAt": "2025-08-06T03:40:20.467Z"
  },
  {
    "id": "6b144140-11ec-4403-a8f7-620401698f7a",
    "title": "Fleabag",
    "description": "A dry-witted woman known only as Fleabag navigates life and love in London while trying to cope with tragedy.",
    "type": "show",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B01LTYIXS6",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b01ltyixs6",
    "imageUrl": "https://image.tmdb.org/t/p/w500/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
    "rating": "TV-MA",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.572Z",
    "updatedAt": "2025-08-06T03:40:20.572Z"
  },
  {
    "id": "14206808-f594-4251-ba68-f2a3e27cf545",
    "title": "The Tomorrow War",
    "description": "A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "amazon-prime",
    "serviceContentId": "B096L2ZDX9",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b096l2zdx9",
    "imageUrl": "https://image.tmdb.org/t/p/w500/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 140,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.676Z",
    "updatedAt": "2025-08-06T03:40:20.676Z"
  },
  {
    "id": "dcc9ec54-f288-4979-b25b-d1b637251d93",
    "title": "Sound of Metal",
    "description": "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
    "type": "movie",
    "genre": "drama",
    "service": "amazon-prime",
    "serviceContentId": "B08P7Q7FZR",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b08p7q7fzr",
    "imageUrl": "https://image.tmdb.org/t/p/w500/7SudKRdLaCGHjlSkjCMMLx9w9Pg.jpg",
    "rating": "R",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.779Z",
    "updatedAt": "2025-08-06T03:40:20.779Z"
  },
  {
    "id": "b3c041d6-d900-4d68-8027-336af86a7e77",
    "title": "Borat Subsequent Moviefilm",
    "description": "Borat returns to America to deliver a prodigious bribe to American regime for benefit of once-glorious nation of Kazakhstan.",
    "type": "movie",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B08MD4QZ9K",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b08md4qz9k",
    "imageUrl": "https://image.tmdb.org/t/p/w500/eduqODhEITMm4KTlFdYdXa5IOtR.jpg",
    "rating": "R",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 95,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.883Z",
    "updatedAt": "2025-08-06T03:40:20.883Z"
  },
  {
    "id": "ad76a114-1e95-458b-8a24-ded493ad6561",
    "title": "ABC World News Tonight",
    "description": "America's most-watched evening news program, delivering the day's biggest stories with David Muir.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "Cy-DXnSXdY0",
    "directUrl": "https://tv.youtube.com/watch/Cy-DXnSXdY0?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.986Z",
    "updatedAt": "2025-08-06T03:40:20.986Z"
  },
  {
    "id": "a4d9b468-00bd-47b8-bf2d-4e246a555cdd",
    "title": "Good Morning America",
    "description": "Start your day with the latest news, weather, and inspiring stories from across America.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "gma-live",
    "directUrl": "https://tv.youtube.com/watch/gma-live",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.088Z",
    "updatedAt": "2025-08-06T03:40:21.088Z"
  },
  {
    "id": "932330a6-2d97-407a-949f-6009e5330911",
    "title": "The Tonight Show Starring Jimmy Fallon",
    "description": "Late-night comedy with celebrity interviews, musical performances, and hilarious sketches.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tonight-show-live",
    "directUrl": "https://tv.youtube.com/watch/tonight-show-live",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.210Z",
    "updatedAt": "2025-08-06T03:40:21.210Z"
  },
  {
    "id": "a2e79150-c3c4-4120-af84-0815872dba72",
    "title": "FOX News",
    "description": "Live breaking news, political analysis, and coverage of the day's most important events from America's newsroom.",
    "type": "live",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "fox-news-live",
    "directUrl": "https://tv.youtube.com/watch/fox-news-live",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.313Z",
    "updatedAt": "2025-08-06T03:40:21.313Z"
  },
  {
    "id": "5035f7c0-7076-4681-9e3f-8b2bea3378e0",
    "title": "CNN Breaking News",
    "description": "Live breaking news coverage and analysis of the day's most important events.",
    "type": "live",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "cnn-breaking",
    "directUrl": "https://tv.youtube.com/watch/cnn-breaking",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.415Z",
    "updatedAt": "2025-08-06T03:40:21.415Z"
  },
  {
    "id": "4d94f35a-d0b9-4091-ab77-465d22e7c79d",
    "title": "Sunday Night Football",
    "description": "The premier Sunday night NFL matchup with expert commentary and analysis.",
    "type": "live",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "snf-live",
    "directUrl": "https://tv.youtube.com/watch/snf-live",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 210,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.518Z",
    "updatedAt": "2025-08-06T03:40:21.518Z"
  },
  {
    "id": "0506d34d-a55d-4344-9daa-2589bbc26812",
    "title": "Happy Gilmore 2",
    "description": "Happy Gilmore returns to the golf course for another hilarious round of unconventional golfing and hockey-style antics.",
    "type": "movie",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "happy-gilmore-2",
    "directUrl": "https://www.netflix.com/title/happy-gilmore-2",
    "imageUrl": "/attached_assets/image_1754437006943.png",
    "rating": "PG-13",
    "year": 2025,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.622Z",
    "updatedAt": "2025-08-06T03:40:21.622Z"
  },
  {
    "id": "netflix-paul-tyson",
    "title": "Jake Paul vs Mike Tyson",
    "description": "The most anticipated boxing match of the decade. YouTube sensation Jake Paul faces off against heavyweight legend Mike Tyson in an epic showdown.",
    "type": "live",
    "genre": "sports",
    "service": "netflix",
    "serviceContentId": "paul-tyson-fight",
    "directUrl": "https://www.netflix.com/title/paul-tyson-fight",
    "imageUrl": "/attached_assets/image_1754368126300.png",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.725Z",
    "updatedAt": "2025-08-06T03:40:21.725Z"
  },
  {
    "id": "cnn-presidential-debate",
    "title": "Presidential Debate 2024",
    "description": "Live coverage of the crucial presidential debate that will shape the future of America. Comprehensive analysis and real-time fact-checking.",
    "type": "live",
    "genre": "news",
    "service": "cnn",
    "serviceContentId": "presidential-debate-2024",
    "directUrl": "https://www.cnn.com/live/presidential-debate-2024",
    "imageUrl": "/attached_assets/image_1754368633196.png",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.828Z",
    "updatedAt": "2025-08-06T03:40:21.828Z"
  },
  {
    "id": "hulu-bill-burr-drop-dead",
    "title": "Bill Burr: Drop Dead Years",
    "description": "Comedy legend Bill Burr delivers his most personal and hilarious stand-up special yet, tackling marriage, parenting, and the absurdities of modern life.",
    "type": "show",
    "genre": "comedy",
    "service": "hulu",
    "serviceContentId": "bill-burr-drop-dead-years",
    "directUrl": "https://www.hulu.com/watch/bill-burr-drop-dead-years",
    "imageUrl": "/attached_assets/image_1754434659807.png",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 75,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.931Z",
    "updatedAt": "2025-08-06T03:40:21.931Z"
  },
  {
    "id": "espn-5",
    "title": "The Last Dance",
    "description": "The definitive documentary series chronicling Michael Jordan and the Chicago Bulls dynasty. An intimate look at the greatest basketball player of all time.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "the-last-dance",
    "directUrl": "https://www.espn.com/watch/player/_/id/the-last-dance",
    "imageUrl": "/attached_assets/image_1754368126300.png",
    "rating": "TV-14",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.035Z",
    "updatedAt": "2025-08-06T03:40:22.035Z"
  },
  {
    "id": "f1870477-9c63-4af6-8df9-3b536d80f765",
    "title": "Monday Night Football",
    "description": "The premier primetime NFL game of the week featuring top matchups and expert commentary.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "mnf-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-mnf",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.195Z",
    "updatedAt": "2025-08-06T03:40:22.195Z"
  },
  {
    "id": "82abed7d-7064-4344-a351-cbc88a50d4b6",
    "title": "College Football Playoff",
    "description": "The biggest games in college football featuring top-ranked teams competing for the national championship.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "cfp-2024",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-cfp",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 240,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.297Z",
    "updatedAt": "2025-08-06T03:40:22.297Z"
  },
  {
    "id": "42a6d1b1-1bdb-464b-9039-8ae60e539295",
    "title": "NBA on ESPN",
    "description": "Live NBA games featuring the best teams and biggest stars in professional basketball.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "nba-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-nba",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 150,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.402Z",
    "updatedAt": "2025-08-06T03:40:22.402Z"
  },
  {
    "id": "ca9c1021-f24c-4f47-8c6e-9f0a78d9a74c",
    "title": "UFC Fight Night",
    "description": "Elite mixed martial arts competition featuring the world's best fighters in octagon action.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "ufc-fight-night",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-ufc",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.505Z",
    "updatedAt": "2025-08-06T03:40:22.505Z"
  },
  {
    "id": "b153c672-2c60-408b-886f-d6c40d6dfd8c",
    "title": "SportsCenter",
    "description": "ESPN's flagship sports news and highlights program covering all the day's biggest sports stories.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "sportscenter-daily",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-sc",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.608Z",
    "updatedAt": "2025-08-06T03:40:22.608Z"
  },
  {
    "id": "a5030acd-224b-4690-9b97-74b9e59bc46c",
    "title": "College GameDay",
    "description": "The premier college football pregame show traveling to the biggest games each Saturday.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "college-gameday",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-cgd",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.711Z",
    "updatedAt": "2025-08-06T03:40:22.711Z"
  },
  {
    "id": "415f91dc-af8f-4b55-acc6-f60d1123556e",
    "title": "MLB on ESPN",
    "description": "Live Major League Baseball games featuring America's pastime with expert commentary.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "mlb-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-mlb",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.814Z",
    "updatedAt": "2025-08-06T03:40:22.814Z"
  },
  {
    "id": "8c72fb09-075a-4d8e-9baf-28b3074af5a6",
    "title": "30 for 30: The Tuck Rule",
    "description": "The controversial call that changed NFL history. An in-depth look at the infamous 2001 AFC Divisional playoff game between the Patriots and Raiders.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "tuck-rule-30for30",
    "directUrl": "https://www.espn.com/watch/player/_/id/tuck-rule-30for30",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-14",
    "year": 2009,
    "artist": null,
    "album": null,
    "duration": 90,
    "isLive": false,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.917Z",
    "updatedAt": "2025-08-06T03:40:22.917Z"
  }
];

export async function seedRealContent() {
  console.log('🌱 Seeding database with real content...');
  
  try {
    // Clear existing content
    await db.delete(content);
    console.log('✅ Cleared existing content');

    // Insert real content
    for (const item of realContent) {
      await db.insert(content).values(item);
    }
    
    console.log(`✅ Seeded ${realContent.length} real content items`);
        console.log('📺 netflix content:', realContent.filter(c => c.service === 'netflix').length);
    console.log('🎬 amazon-prime content:', realContent.filter(c => c.service === 'amazon-prime').length);
    console.log('📺 youtube-tv content:', realContent.filter(c => c.service === 'youtube-tv').length);
    console.log('📰 cnn content:', realContent.filter(c => c.service === 'cnn').length);
    console.log('🎭 hulu content:', realContent.filter(c => c.service === 'hulu').length);
    console.log('🏈 espn-plus content:', realContent.filter(c => c.service === 'espn-plus').length);
    console.log('🎯 All content synchronized from database');
    console.log('🚀 Seed file auto-updated with current database state');
    
  } catch (error) {
    console.error('❌ Error seeding content:', error);
    throw error;
  }
}

// Auto-run seeding if this file is executed directly  
if (import.meta.url === `file://${process.argv[1]}`) {
  seedRealContent()
    .then(() => {
      console.log('✅ Seeding completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Seeding failed:', error);
      process.exit(1);
    });
}
