import { db } from './db';
import { content } from '@shared/schema';

// Auto-generated seed file - Last updated: 2025-08-07T03:34:14.415Z
// Total items: 118
const realContent = [
  {
    "id": "espn-5",
    "title": "The Last Dance",
    "description": "The definitive documentary series chronicling Michael Jordan and the Chicago Bulls dynasty. An intimate look at the greatest basketball player of all time.",
    "type": "show",
    "genre": "sports",
    "service": "netflix",
    "serviceContentId": "81002655",
    "directUrl": "https://www.netflix.com/watch/81002655?trackId=268410292&tctx=0%2C0%2Ca956c732-a018-4147-bc02-082cc9692996-231243474%2Ca956c732-a018-4147-bc02-082cc9692996-231243474%7C2%2Cunknown%2C%2C%2CtitlesResults%2C%2CVideo%3A80203144%2CdetailsPagePlayButton",
    "imageUrl": "https://image.tmdb.org/t/p/w500/oVf4xGGbDtwVHiKn8uTuSriY7PH.jpg",
    "rating": "TV-14",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.035Z",
    "updatedAt": "2025-08-07T02:52:52.976Z"
  },
  {
    "id": "ytv-disney-1",
    "title": "The Owl House",
    "description": "Animated series following Luz, a teenage girl who stumbles into a magical world.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "disney-owl-house",
    "directUrl": "https://tv.youtube.com/watch/disney-owl-house?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/fyPAvJIbRSZXZ2idOWT7wPJmBPY.jpg",
    "rating": "TV-Y7",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-07T03:05:39.173Z"
  },
  {
    "id": "ytv-amc-2",
    "title": "Better Call Saul",
    "description": "The transformation of small-time lawyer Jimmy McGill into criminal lawyer Saul Goodman.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "amc-better-call-saul",
    "directUrl": "https://tv.youtube.com/watch/amc-better-call-saul?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-fs2-1",
    "title": "MLB on Fox",
    "description": "Major League Baseball games with comprehensive coverage and expert commentary.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "fs2-mlb-live",
    "directUrl": "https://tv.youtube.com/watch/fs2-mlb-live?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/fox-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-fs2-2",
    "title": "NASCAR Race Hub",
    "description": "The latest NASCAR news, highlights, and analysis from the track.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "fs2-nascar-hub",
    "directUrl": "https://tv.youtube.com/watch/fs2-nascar-hub?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/sports-icon.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "14206808-f594-4251-ba68-f2a3e27cf545",
    "title": "The Tomorrow War",
    "description": "A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "amazon-prime",
    "serviceContentId": "B096L2ZDX9",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b096l2zdx9",
    "imageUrl": "https://image.tmdb.org/t/p/w500/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 140,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.676Z",
    "updatedAt": "2025-08-07T02:49:30.310Z"
  },
  {
    "id": "9d5907f1-329b-4f48-96eb-4314b6fa7def",
    "title": "Glass Onion: A Knives Out Mystery",
    "description": "Detective Benoit Blanc travels to Greece to peel back the layers of a mystery involving a new cast of colorful suspects.",
    "type": "movie",
    "genre": "mystery",
    "service": "netflix",
    "serviceContentId": "81458416",
    "directUrl": "https://www.netflix.com/watch/81458416",
    "imageUrl": "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 139,
    "isLive": false,
    "category": "90%+ on Rotten Tomatoes",
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.951Z",
    "updatedAt": "2025-08-07T02:49:30.745Z"
  },
  {
    "id": "f3dbf649-8fc5-4c41-ab7b-d664fa1ba7f0",
    "title": "Red Notice",
    "description": "An FBI profiler pursuing the world's most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who's always one step ahead.",
    "type": "movie",
    "genre": "action",
    "service": "netflix",
    "serviceContentId": "81161626",
    "directUrl": "https://www.netflix.com/title/81161626",
    "imageUrl": "https://image.tmdb.org/t/p/w500/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 118,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.847Z",
    "updatedAt": "2025-08-07T02:49:31.181Z"
  },
  {
    "id": "457d714f-468d-4886-af83-b441ac439631",
    "title": "The Boys",
    "description": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    "type": "show",
    "genre": "action",
    "service": "amazon-prime",
    "serviceContentId": "B0875JNV76",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b0875jnv76",
    "imageUrl": "https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
    "rating": "TV-MA",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.054Z",
    "updatedAt": "2025-08-07T02:52:56.133Z"
  },
  {
    "id": "3bd2b46e-1ea5-4363-8af9-43d7aef2040b",
    "title": "Squid Game",
    "description": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    "type": "show",
    "genre": "thriller",
    "service": "netflix",
    "serviceContentId": "81040344",
    "directUrl": "https://www.netflix.com/title/81040344",
    "imageUrl": "https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    "rating": "TV-MA",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.430Z",
    "updatedAt": "2025-08-07T02:52:58.206Z"
  },
  {
    "id": "db02bbc6-2190-4d05-b6ea-bc18cdaa6b8c",
    "title": "Wednesday",
    "description": "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    "type": "show",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "81231974",
    "directUrl": "https://www.netflix.com/title/81231974",
    "imageUrl": "https://image.tmdb.org/t/p/w500/kKwy8QiXyQocbDj4haUG0uD1SbF.jpg",
    "rating": "TV-14",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 45,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.326Z",
    "updatedAt": "2025-08-07T02:52:58.720Z"
  },
  {
    "id": "928a1501-97dd-427c-b93b-157d9821a14c",
    "title": "Stranger Things",
    "description": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    "type": "show",
    "genre": "sci-fi",
    "service": "netflix",
    "serviceContentId": "80057281",
    "directUrl": "https://www.netflix.com/title/80057281",
    "imageUrl": "https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    "rating": "TV-14",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 51,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.219Z",
    "updatedAt": "2025-08-07T02:52:59.266Z"
  },
  {
    "id": "4d94f35a-d0b9-4091-ab77-465d22e7c79d",
    "title": "Sunday Night Football",
    "description": "The premier Sunday night NFL matchup with expert commentary and analysis.",
    "type": "live",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "snf-live",
    "directUrl": "https://tv.youtube.com/watch/snf-live",
    "imageUrl": "/attached_assets/image_1754436760814.png",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 210,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.518Z",
    "updatedAt": "2025-08-06T03:40:21.518Z"
  },
  {
    "id": "932330a6-2d97-407a-949f-6009e5330911",
    "title": "The Tonight Show Starring Jimmy Fallon",
    "description": "Late-night comedy with celebrity interviews, musical performances, and hilarious sketches.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tonight-show-live",
    "directUrl": "https://tv.youtube.com/watch/tonight-show-live",
    "imageUrl": "/src/assets/network-logos/nbc-official.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.210Z",
    "updatedAt": "2025-08-06T03:40:21.210Z"
  },
  {
    "id": "netflix-paul-tyson",
    "title": "Jake Paul vs Mike Tyson",
    "description": "The most anticipated boxing match of the decade. YouTube sensation Jake Paul faces off against heavyweight legend Mike Tyson in an epic showdown.",
    "type": "live",
    "genre": "sports",
    "service": "netflix",
    "serviceContentId": "paul-tyson-fight",
    "directUrl": "https://www.netflix.com/title/paul-tyson-fight",
    "imageUrl": "/attached_assets/image_1754368126300.png",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.725Z",
    "updatedAt": "2025-08-06T03:40:21.725Z"
  },
  {
    "id": "cnn-presidential-debate",
    "title": "Presidential Debate 2024",
    "description": "Live coverage of the crucial presidential debate that will shape the future of America. Comprehensive analysis and real-time fact-checking.",
    "type": "live",
    "genre": "news",
    "service": "cnn",
    "serviceContentId": "presidential-debate-2024",
    "directUrl": "https://www.cnn.com/live/presidential-debate-2024",
    "imageUrl": "/attached_assets/image_1754368633196.png",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.828Z",
    "updatedAt": "2025-08-06T03:40:21.828Z"
  },
  {
    "id": "dcc9ec54-f288-4979-b25b-d1b637251d93",
    "title": "Sound of Metal",
    "description": "A heavy-metal drummer's life is thrown into freefall when he begins to lose his hearing.",
    "type": "movie",
    "genre": "drama",
    "service": "amazon-prime",
    "serviceContentId": "B08P7Q7FZR",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b08p7q7fzr",
    "imageUrl": "https://image.tmdb.org/t/p/w500/3178oOJKKPDeQ2legWQvMPpllv.jpg",
    "rating": "R",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "category": "Critically Acclaimed",
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.779Z",
    "updatedAt": "2025-08-07T02:49:29.875Z"
  },
  {
    "id": "ad76a114-1e95-458b-8a24-ded493ad6561",
    "title": "ABC World News Tonight",
    "description": "America's most-watched evening news program, delivering the day's biggest stories with David Muir.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "Cy-DXnSXdY0",
    "directUrl": "https://tv.youtube.com/watch/Cy-DXnSXdY0?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/abc-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.986Z",
    "updatedAt": "2025-08-06T03:40:20.986Z"
  },
  {
    "id": "f1870477-9c63-4af6-8df9-3b536d80f765",
    "title": "Monday Night Football",
    "description": "The premier primetime NFL game of the week featuring top matchups and expert commentary.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "mnf-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-mnf",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.195Z",
    "updatedAt": "2025-08-06T03:40:22.195Z"
  },
  {
    "id": "82abed7d-7064-4344-a351-cbc88a50d4b6",
    "title": "College Football Playoff",
    "description": "The biggest games in college football featuring top-ranked teams competing for the national championship.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "cfp-2024",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-cfp",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 240,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.297Z",
    "updatedAt": "2025-08-06T03:40:22.297Z"
  },
  {
    "id": "42a6d1b1-1bdb-464b-9039-8ae60e539295",
    "title": "NBA on ESPN",
    "description": "Live NBA games featuring the best teams and biggest stars in professional basketball.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "nba-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-nba",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 150,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.402Z",
    "updatedAt": "2025-08-06T03:40:22.402Z"
  },
  {
    "id": "ca9c1021-f24c-4f47-8c6e-9f0a78d9a74c",
    "title": "UFC Fight Night",
    "description": "Elite mixed martial arts competition featuring the world's best fighters in octagon action.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "ufc-fight-night",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-ufc",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.505Z",
    "updatedAt": "2025-08-06T03:40:22.505Z"
  },
  {
    "id": "415f91dc-af8f-4b55-acc6-f60d1123556e",
    "title": "MLB on ESPN",
    "description": "Live Major League Baseball games featuring America's pastime with expert commentary.",
    "type": "live",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "mlb-live",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-mlb",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.814Z",
    "updatedAt": "2025-08-06T03:40:22.814Z"
  },
  {
    "id": "a4d9b468-00bd-47b8-bf2d-4e246a555cdd",
    "title": "Good Morning America",
    "description": "Start your day with the latest news, weather, and inspiring stories from across America.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "gma-live",
    "directUrl": "https://tv.youtube.com/watch/gma-live",
    "imageUrl": "/src/assets/network-logos/abc-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.088Z",
    "updatedAt": "2025-08-06T03:40:21.088Z"
  },
  {
    "id": "a2e79150-c3c4-4120-af84-0815872dba72",
    "title": "FOX News",
    "description": "Live breaking news, political analysis, and coverage of the day's most important events from America's newsroom.",
    "type": "live",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "fox-news-live",
    "directUrl": "https://tv.youtube.com/watch/fox-news-live",
    "imageUrl": "/src/assets/network-logos/fox-official.svg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.313Z",
    "updatedAt": "2025-08-06T03:40:21.313Z"
  },
  {
    "id": "5035f7c0-7076-4681-9e3f-8b2bea3378e0",
    "title": "CNN Breaking News",
    "description": "Live breaking news coverage and analysis of the day's most important events.",
    "type": "live",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "cnn-breaking",
    "directUrl": "https://tv.youtube.com/watch/cnn-breaking",
    "imageUrl": "/src/assets/network-logos/cnn-official.svg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.415Z",
    "updatedAt": "2025-08-06T03:40:21.415Z"
  },
  {
    "id": "8c72fb09-075a-4d8e-9baf-28b3074af5a6",
    "title": "30 for 30: The Tuck Rule",
    "description": "The controversial call that changed NFL history. An in-depth look at the infamous 2001 AFC Divisional playoff game between the Patriots and Raiders.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "tuck-rule-30for30",
    "directUrl": "https://www.espn.com/watch/player/_/id/tuck-rule-30for30",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-14",
    "year": 2009,
    "artist": null,
    "album": null,
    "duration": 90,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.917Z",
    "updatedAt": "2025-08-06T03:40:22.917Z"
  },
  {
    "id": "ytv-tnt-5",
    "title": "Law & Order",
    "description": "Classic crime procedural following police investigations and courtroom drama.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "tnt-law-order",
    "directUrl": "https://tv.youtube.com/watch/tnt-law-order?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/n2NxrkG3KpZ6FwALqi5uiZF8zXC.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-07T03:05:36.453Z"
  },
  {
    "id": "ytv-tbs-3",
    "title": "Friends",
    "description": "Classic sitcom about six friends navigating life and love in New York City.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tbs-friends",
    "directUrl": "https://tv.youtube.com/watch/tbs-friends?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/5rX8bngVFjDK0414JnDYZIVIP1A.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-07T03:05:36.871Z"
  },
  {
    "id": "ytv-tbs-4",
    "title": "American Dad!",
    "description": "Animated sitcom about a conservative CIA agent and his unconventional family.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tbs-american-dad",
    "directUrl": "https://tv.youtube.com/watch/tbs-american-dad?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/j84ZtVRoxKWTsQUya77um4l8Dqs.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "ytv-tbs-5",
    "title": "Family Guy",
    "description": "Animated comedy about the Griffin family and their outrageous adventures.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tbs-family-guy",
    "directUrl": "https://tv.youtube.com/watch/tbs-family-guy?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/8o8kiBkWFK3gVytHdyzEWUBXVfK.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "ytv-discovery-2",
    "title": "MythBusters",
    "description": "Science entertainment show testing the validity of myths and urban legends.",
    "type": "show",
    "genre": "documentary",
    "service": "youtube-tv",
    "serviceContentId": "discovery-mythbusters",
    "directUrl": "https://tv.youtube.com/watch/discovery-mythbusters?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/lvRnMu00NLGiTPijGZg9CRF3nuY.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-tbs-6",
    "title": "The Misery Index",
    "description": "Game show where contestants rate real-life miserable events for cash prizes.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tbs-misery-index",
    "directUrl": "https://tv.youtube.com/watch/tbs-misery-index?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/fEJPYiMCT1c8Pd5g9SlkbGSq9NU.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "ytv-tnt-4",
    "title": "All Elite Wrestling: Dynamite",
    "description": "Live professional wrestling featuring top AEW superstars in action-packed matches.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "tnt-aew-dynamite",
    "directUrl": "https://tv.youtube.com/watch/tnt-aew-dynamite?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/itLcy79zMVU9K4OTU4h8I61nPJi.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "ytv-tnt-3",
    "title": "Animal Kingdom",
    "description": "Crime drama following a Southern California family involved in criminal activities.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "tnt-animal-kingdom",
    "directUrl": "https://tv.youtube.com/watch/tnt-animal-kingdom?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/rzvdKrnSRKPFI0pgqMQknDPpRC9.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "ytv-tnt-6",
    "title": "NBA Tip-Off",
    "description": "Pre-game analysis and highlights before live NBA games on TNT.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "tnt-nba-tipoff",
    "directUrl": "https://tv.youtube.com/watch/tnt-nba-tipoff?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/sports-icon.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:35:04.805Z",
    "updatedAt": "2025-08-06T04:35:04.805Z"
  },
  {
    "id": "nf-movie-1",
    "title": "Glass Onion: A Knives Out Mystery",
    "description": "Detective Benoit Blanc travels to Greece to solve a murder mystery involving a tech billionaire and his eccentric friends.",
    "type": "movie",
    "genre": "mystery",
    "service": "netflix",
    "serviceContentId": "glass-onion",
    "directUrl": "https://www.netflix.com/title/81458416",
    "imageUrl": "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 139,
    "isLive": false,
    "category": "90%+ on Rotten Tomatoes",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:22.805Z"
  },
  {
    "id": "nf-movie-2",
    "title": "Red Notice",
    "description": "An FBI profiler must partner with the worlds most wanted art thief to catch an elusive criminal.",
    "type": "movie",
    "genre": "action",
    "service": "netflix",
    "serviceContentId": "red-notice",
    "directUrl": "https://www.netflix.com/title/81161626",
    "imageUrl": "https://image.tmdb.org/t/p/w500/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 118,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:23.250Z"
  },
  {
    "id": "nf-movie-3",
    "title": "The Adam Project",
    "description": "A time-traveling pilot teams up with his younger self and late father to save the future.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "netflix",
    "serviceContentId": "the-adam-project",
    "directUrl": "https://www.netflix.com/title/81309354",
    "imageUrl": "https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 106,
    "isLive": false,
    "category": "Comedies",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:23.692Z"
  },
  {
    "id": "0506d34d-a55d-4344-9daa-2589bbc26812",
    "title": "Happy Gilmore 2",
    "description": "Happy Gilmore returns to the golf course for another hilarious round of unconventional golfing and hockey-style antics.",
    "type": "movie",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "happy-gilmore-2",
    "directUrl": "https://www.netflix.com/title/happy-gilmore-2",
    "imageUrl": "https://image.tmdb.org/t/p/w500/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
    "rating": "PG-13",
    "year": 2025,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.622Z",
    "updatedAt": "2025-08-07T02:49:29.001Z"
  },
  {
    "id": "b3c041d6-d900-4d68-8027-336af86a7e77",
    "title": "Borat Subsequent Moviefilm",
    "description": "Borat returns to America to deliver a prodigious bribe to American regime for benefit of once-glorious nation of Kazakhstan.",
    "type": "movie",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B08MD4QZ9K",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b08md4qz9k",
    "imageUrl": "https://image.tmdb.org/t/p/w500/3L1Ml5RWjFVfVq3rQENvgFymT0U.jpg",
    "rating": "R",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 95,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.883Z",
    "updatedAt": "2025-08-07T02:49:29.440Z"
  },
  {
    "id": "hulu-movie-1",
    "title": "Palm Springs",
    "description": "Two wedding guests find themselves stuck in a time loop at a Palm Springs wedding.",
    "type": "movie",
    "genre": "comedy",
    "service": "hulu",
    "serviceContentId": "palm-springs",
    "directUrl": "https://www.hulu.com/movie/palm-springs-6b09ee79-2f78-484e-aa9d-5e0735e6a6c8",
    "imageUrl": "https://image.tmdb.org/t/p/w500/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg",
    "rating": "R",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 90,
    "isLive": false,
    "category": "90%+ on Rotten Tomatoes",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:51.189Z"
  },
  {
    "id": "hulu-movie-2",
    "title": "Nomadland",
    "description": "A woman embarks on a journey through the American West after losing everything in the recession.",
    "type": "movie",
    "genre": "drama",
    "service": "hulu",
    "serviceContentId": "nomadland",
    "directUrl": "https://www.hulu.com/movie/nomadland-7cc5e816-bd4f-4e7d-8ca5-c6f71a5a1d1a",
    "imageUrl": "https://image.tmdb.org/t/p/w500/k5XzjWihzum1YgLMlqRDRZDmVMn.jpg",
    "rating": "R",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 107,
    "isLive": false,
    "category": "Critically Acclaimed",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:51.644Z"
  },
  {
    "id": "hulu-movie-3",
    "title": "Run",
    "description": "A homeschooled teenager begins to suspect her mother is keeping a dark secret from her.",
    "type": "movie",
    "genre": "thriller",
    "service": "hulu",
    "serviceContentId": "run-2020",
    "directUrl": "https://www.hulu.com/movie/run-4c8b9c8e-3f2a-4e5d-9b1f-8a7c6d5e4f3g",
    "imageUrl": "https://image.tmdb.org/t/p/w500/ilHG4EayOVoYeKqslspY3pR4wzC.jpg",
    "rating": "PG-13",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 90,
    "isLive": false,
    "category": "Popular in the US Today",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:52.082Z"
  },
  {
    "id": "hbo-movie-1",
    "title": "Dune",
    "description": "Paul Atreides leads nomadic tribes in a revolt against the evil Harkonnen family on the desert planet Arrakis.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "hbo-max",
    "serviceContentId": "dune-2021",
    "directUrl": "https://play.hbomax.com/movie/urn:hbo:movie:GYbX2vQqutJ68uwEAAABc",
    "imageUrl": "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 155,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:52.527Z"
  },
  {
    "id": "hbo-movie-2",
    "title": "The Matrix Resurrections",
    "description": "Neo must choose to follow the white rabbit once more in this sequel to the Matrix trilogy.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "hbo-max",
    "serviceContentId": "matrix-resurrections",
    "directUrl": "https://play.hbomax.com/movie/urn:hbo:movie:GYc8X2wqu_568uwEAAABd",
    "imageUrl": "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    "rating": "R",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 148,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:52.966Z"
  },
  {
    "id": "hbo-movie-3",
    "title": "King Richard",
    "description": "The story of how Richard Williams trained his daughters Venus and Williams to become tennis legends.",
    "type": "movie",
    "genre": "biography",
    "service": "hbo-max",
    "serviceContentId": "king-richard",
    "directUrl": "https://play.hbomax.com/movie/urn:hbo:movie:GYd9X3xru_678uwEAAABe",
    "imageUrl": "https://image.tmdb.org/t/p/w500/2dfujXrxePtYJPiPHj1HkAFQvpu.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 144,
    "isLive": false,
    "category": "Critically Acclaimed",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:46:53.406Z"
  },
  {
    "id": "prime-movie-1",
    "title": "Coming 2 America",
    "description": "Prince Akeem discovers he has a long-lost son and returns to America to meet his heir.",
    "type": "movie",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "coming-2-america",
    "directUrl": "https://www.amazon.com/dp/B08WJG6RKZ",
    "imageUrl": "https://image.tmdb.org/t/p/w500/nWBPLkqNApY5pgrJFMiI9joSI30.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 110,
    "isLive": false,
    "category": "Comedies",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:24.139Z"
  },
  {
    "id": "prime-movie-2",
    "title": "The Tomorrow War",
    "description": "A family man is drafted to fight in a future war where humanitys fate depends on his ability to confront his past.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "amazon-prime",
    "serviceContentId": "tomorrow-war",
    "directUrl": "https://www.amazon.com/dp/B096TJK8F2",
    "imageUrl": "https://image.tmdb.org/t/p/w500/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 138,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:24.581Z"
  },
  {
    "id": "prime-movie-3",
    "title": "Sound of Metal",
    "description": "A heavy-metal drummer begins to lose his hearing and must face a future filled with silence.",
    "type": "movie",
    "genre": "drama",
    "service": "amazon-prime",
    "serviceContentId": "sound-of-metal",
    "directUrl": "https://www.amazon.com/dp/B08P4Z8Q9K",
    "imageUrl": "https://image.tmdb.org/t/p/w500/3178oOJKKPDeQ2legWQvMPpllv.jpg",
    "rating": "R",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "category": "Critically Acclaimed",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:25.024Z"
  },
  {
    "id": "apple-movie-1",
    "title": "CODA",
    "description": "A deaf teenager pursues her passion for music while helping her familys struggling fishing business.",
    "type": "movie",
    "genre": "drama",
    "service": "apple-tv",
    "serviceContentId": "coda",
    "directUrl": "https://tv.apple.com/movie/coda/umc.cmc.3eh9r5iz32ggdm4ccvw5igiir",
    "imageUrl": "https://image.tmdb.org/t/p/w500/BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 111,
    "isLive": false,
    "category": "Critically Acclaimed",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:25.467Z"
  },
  {
    "id": "apple-movie-2",
    "title": "Finch",
    "description": "A man, a robot, and a dog form an unlikely family in a post-apocalyptic world.",
    "type": "movie",
    "genre": "sci-fi",
    "service": "apple-tv",
    "serviceContentId": "finch",
    "directUrl": "https://tv.apple.com/movie/finch/umc.cmc.4eq7d2p6wj2a6f5z4pf2qxd4x",
    "imageUrl": "https://image.tmdb.org/t/p/w500/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg",
    "rating": "PG-13",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 115,
    "isLive": false,
    "category": "Your Next Watch",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:25.909Z"
  },
  {
    "id": "apple-movie-3",
    "title": "The Tragedy of Macbeth",
    "description": "Joel Coens bold adaptation of Shakespeares classic tale of murder, madness, ambition and wrathful cunning.",
    "type": "movie",
    "genre": "drama",
    "service": "apple-tv",
    "serviceContentId": "macbeth",
    "directUrl": "https://tv.apple.com/movie/the-tragedy-of-macbeth/umc.cmc.4h7k3x2e8fry8m5s9fg9g5h3w",
    "imageUrl": "https://image.tmdb.org/t/p/w500/tDNJEhcLbX3jIk3BMCur9pCdaVD.jpg",
    "rating": "R",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 105,
    "isLive": false,
    "category": "Popular in the US Today",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:26.350Z"
  },
  {
    "id": "disney-movie-1",
    "title": "Encanto",
    "description": "A Colombian teenage girl may be her familys last hope when she discovers that the magic surrounding her family is in danger.",
    "type": "movie",
    "genre": "family",
    "service": "disney-plus",
    "serviceContentId": "encanto",
    "directUrl": "https://www.disneyplus.com/movies/encanto/33q7DY1rtHQH",
    "imageUrl": "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    "rating": "PG",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 102,
    "isLive": false,
    "category": "90%+ on Rotten Tomatoes",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:22.363Z"
  },
  {
    "id": "paramount-movie-1",
    "title": "Top Gun: Maverick",
    "description": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation of pilots.",
    "type": "movie",
    "genre": "action",
    "service": "paramount-plus",
    "serviceContentId": "top-gun-maverick",
    "directUrl": "https://www.paramountplus.com/movies/top-gun-maverick/5vj8X2wqu_568uwEAAABf",
    "imageUrl": "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 130,
    "isLive": false,
    "category": "Action & Adventure",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:26.796Z"
  },
  {
    "id": "paramount-movie-2",
    "title": "Scream",
    "description": "A new Ghostface killer terrorizes the town of Woodsboro, targeting teenagers related to the original murders.",
    "type": "movie",
    "genre": "horror",
    "service": "paramount-plus",
    "serviceContentId": "scream-2022",
    "directUrl": "https://www.paramountplus.com/movies/scream/6wk9Y3xsu_679vwFAAABg",
    "imageUrl": "https://image.tmdb.org/t/p/w500/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
    "rating": "R",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 114,
    "isLive": false,
    "category": "Popular in the US Today",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:27.240Z"
  },
  {
    "id": "paramount-movie-3",
    "title": "The Lost City",
    "description": "A reclusive romance novelist gets caught up in a kidnapping attempt that mirrors her latest book.",
    "type": "movie",
    "genre": "comedy",
    "service": "paramount-plus",
    "serviceContentId": "the-lost-city",
    "directUrl": "https://www.paramountplus.com/movies/the-lost-city/7xl0Z4ytv_780xwGAAABh",
    "imageUrl": "https://image.tmdb.org/t/p/w500/rnheO8cFvCYcmZsDrBoabJbKLFE.jpg",
    "rating": "PG-13",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 112,
    "isLive": false,
    "category": "Comedies",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:27.682Z"
  },
  {
    "id": "disney-movie-2",
    "title": "Turning Red",
    "description": "A thirteen-year-old girl turns into a giant red panda whenever she gets too excited.",
    "type": "movie",
    "genre": "family",
    "service": "disney-plus",
    "serviceContentId": "turning-red",
    "directUrl": "https://www.disneyplus.com/movies/turning-red/4mFHrEHJjGha",
    "imageUrl": "https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    "rating": "PG",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 100,
    "isLive": false,
    "category": "Comedies",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:28.123Z"
  },
  {
    "id": "disney-movie-3",
    "title": "Luca",
    "description": "A young boy experiences an unforgettable summer filled with gelato, pasta and endless scooter rides on the Italian Riviera.",
    "type": "movie",
    "genre": "family",
    "service": "disney-plus",
    "serviceContentId": "luca",
    "directUrl": "https://www.disneyplus.com/movies/luca/7K1HyQ6Hl48s",
    "imageUrl": "https://image.tmdb.org/t/p/w500/9x4i9uKGXt8IiiIF5Ey0DIoY738.jpg",
    "rating": "PG",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 95,
    "isLive": false,
    "category": "90%+ on Rotten Tomatoes",
    "availability": null,
    "createdAt": "2025-08-06T04:49:22.858Z",
    "updatedAt": "2025-08-07T02:49:28.562Z"
  },
  {
    "id": "1ae785d8-068b-477a-9709-a20e242bc65b",
    "title": "Ozark",
    "description": "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.",
    "type": "show",
    "genre": "crime",
    "service": "netflix",
    "serviceContentId": "80117552",
    "directUrl": "https://www.netflix.com/watch/80117552",
    "imageUrl": "https://image.tmdb.org/t/p/w500/m73bD8VjibSKuTWg597GQVyVhSb.jpg",
    "rating": "TV-MA",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.639Z",
    "updatedAt": "2025-08-07T02:52:57.120Z"
  },
  {
    "id": "933389b6-646e-4128-9de4-fd88c232f0f3",
    "title": "The Crown",
    "description": "This drama follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    "type": "show",
    "genre": "drama",
    "service": "netflix",
    "serviceContentId": "80025678",
    "directUrl": "https://www.netflix.com/title/80025678",
    "imageUrl": "https://image.tmdb.org/t/p/w500/1DDE0Z2Y805rqfkEjPbZsMLyPwa.jpg",
    "rating": "TV-MA",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.533Z",
    "updatedAt": "2025-08-07T02:52:57.682Z"
  },
  {
    "id": "ytv-tbs-1",
    "title": "Conan OBrien Must Go",
    "description": "Comedy legend Conan OBrien travels the world bringing his unique brand of humor to new audiences.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "conan-tbs",
    "directUrl": "https://tv.youtube.com/watch/conan-tbs?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/x0Rt2LBQ1nuRq51lKyvETERU5zs.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-07T03:05:49.989Z"
  },
  {
    "id": "hulu-bill-burr-drop-dead",
    "title": "Bill Burr: Drop Dead Years",
    "description": "Comedy legend Bill Burr delivers his most personal and hilarious stand-up special yet, tackling marriage, parenting, and the absurdities of modern life.",
    "type": "show",
    "genre": "comedy",
    "service": "hulu",
    "serviceContentId": "bill-burr-drop-dead-years",
    "directUrl": "https://www.hulu.com/watch/bill-burr-drop-dead-years",
    "imageUrl": "/attached_assets/image_1754434659807.png",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 75,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:21.931Z",
    "updatedAt": "2025-08-06T03:40:21.931Z"
  },
  {
    "id": "b153c672-2c60-408b-886f-d6c40d6dfd8c",
    "title": "SportsCenter",
    "description": "ESPN's flagship sports news and highlights program covering all the day's biggest sports stories.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "sportscenter-daily",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-sc",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.608Z",
    "updatedAt": "2025-08-06T03:40:22.608Z"
  },
  {
    "id": "a5030acd-224b-4690-9b97-74b9e59bc46c",
    "title": "College GameDay",
    "description": "The premier college football pregame show traveling to the biggest games each Saturday.",
    "type": "show",
    "genre": "sports",
    "service": "espn-plus",
    "serviceContentId": "college-gameday",
    "directUrl": "https://www.espn.com/watch/player/_/id/espn-plus-cgd",
    "imageUrl": "https://a.espncdn.com/combiner/i?img=%2Fi%2Fespn%2Fespn_logos%2Fespn_red.png&w=300&h=200&scale=crop&cquality=80&location=origin&format=jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:22.711Z",
    "updatedAt": "2025-08-06T03:40:22.711Z"
  },
  {
    "id": "6b144140-11ec-4403-a8f7-620401698f7a",
    "title": "Fleabag",
    "description": "A dry-witted woman known only as Fleabag navigates life and love in London while trying to cope with tragedy.",
    "type": "show",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B01LTYIXS6",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b01ltyixs6",
    "imageUrl": "https://image.tmdb.org/t/p/w500/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
    "rating": "TV-MA",
    "year": 2016,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.572Z",
    "updatedAt": "2025-08-07T02:52:53.808Z"
  },
  {
    "id": "7fbba768-cf84-4d58-9892-dd2eb5f8b8a0",
    "title": "Invincible",
    "description": "Teen Mark Grayson inherits his father's superpowers and learns that his legendary dad may not be who he thought he was.",
    "type": "show",
    "genre": "animation",
    "service": "amazon-prime",
    "serviceContentId": "B00BQJMRWI",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b00bqjmrwi",
    "imageUrl": "https://image.tmdb.org/t/p/w500/jBn4LWlgdsf6xIUYhYBwpctBVsj.jpg",
    "rating": "TV-MA",
    "year": 2021,
    "artist": null,
    "album": null,
    "duration": 45,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.467Z",
    "updatedAt": "2025-08-07T02:52:54.252Z"
  },
  {
    "id": "e9500b82-b38a-469a-a97c-bb23370dea34",
    "title": "The Lord of the Rings: The Rings of Power",
    "description": "Epic drama set thousands of years before the events of J.R.R. Tolkien's The Hobbit and The Lord of the Rings follows an ensemble cast of characters.",
    "type": "show",
    "genre": "fantasy",
    "service": "amazon-prime",
    "serviceContentId": "B0B5SV1RTM",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b0b5sv1rtm",
    "imageUrl": "https://image.tmdb.org/t/p/w500/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    "rating": "TV-14",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 70,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.364Z",
    "updatedAt": "2025-08-07T02:52:54.692Z"
  },
  {
    "id": "94162723-3dc9-414f-8265-b45569a80941",
    "title": "Tom Clancy's Jack Ryan",
    "description": "An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment as he uncovers a pattern in terrorist communication.",
    "type": "show",
    "genre": "thriller",
    "service": "amazon-prime",
    "serviceContentId": "B07GC2KLBY",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b07gc2klby",
    "imageUrl": "https://image.tmdb.org/t/p/w500/cO4py3L3q5GNPrA0qr1wVDrosK1.jpg",
    "rating": "TV-14",
    "year": 2018,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.261Z",
    "updatedAt": "2025-08-07T02:52:55.131Z"
  },
  {
    "id": "36848caa-1dd7-4526-9c3c-e89d230674a1",
    "title": "The Marvelous Mrs. Maisel",
    "description": "A housewife in 1958 decides to become a stand-up comic.",
    "type": "show",
    "genre": "comedy",
    "service": "amazon-prime",
    "serviceContentId": "B077RMZL8J",
    "directUrl": "https://app.primevideo.com/detail?gti=amzn1.dv.gti.b077rmzl8j",
    "imageUrl": "https://image.tmdb.org/t/p/w500/zS7fQiOZiKCVH2vlYSiIsFWW8hh.jpg",
    "rating": "TV-14",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 50,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:20.158Z",
    "updatedAt": "2025-08-07T02:52:55.647Z"
  },
  {
    "id": "b34776ab-fee7-4da6-a66c-5e5c43c9c1b5",
    "title": "Dark",
    "description": "A missing child causes four families to help each other for answers. What they discover is something far more mysterious than they ever imagined.",
    "type": "show",
    "genre": "sci-fi",
    "service": "netflix",
    "serviceContentId": "80100172",
    "directUrl": "https://www.netflix.com/title/80100172",
    "imageUrl": "https://image.tmdb.org/t/p/w500/1DLjjvSWMYo17B7wuz6YikB96hH.jpg",
    "rating": "TV-MA",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T03:40:19.744Z",
    "updatedAt": "2025-08-07T02:52:56.629Z"
  },
  {
    "id": "ytv-pbs-2",
    "title": "Nature",
    "description": "Stunning wildlife documentaries showcasing the natural worlds most incredible animals and ecosystems.",
    "type": "show",
    "genre": "documentary",
    "service": "youtube-tv",
    "serviceContentId": "nature-pbs",
    "directUrl": "https://tv.youtube.com/watch/nature-pbs?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/zYjTfivQUy4NGdrzqJVzVHke5sW.jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-07T03:05:52.922Z"
  },
  {
    "id": "ytv-fox-2",
    "title": "The Simpsons",
    "description": "Americas favorite animated family continues their hilarious adventures in Springfield.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "simpsons-fox",
    "directUrl": "https://tv.youtube.com/watch/simpsons-fox?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/vHqeLzYl3dEAutojCO26g0LIkom.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-fox-1",
    "title": "FOX News",
    "description": "Breaking news and analysis with the latest headlines from politics, business, and world events.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "fox-news-live",
    "directUrl": "https://tv.youtube.com/watch/fox-news-live?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/fox-official.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-pbs-1",
    "title": "PBS NewsHour",
    "description": "In-depth analysis of the days news with comprehensive reporting on national and international events.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "pbs-newshour",
    "directUrl": "https://tv.youtube.com/watch/pbs-newshour?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/pbs-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-abc-1",
    "title": "ABC World News Tonight",
    "description": "Americas most-watched evening news program, delivering the days biggest stories with David Muir.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "abc-world-news",
    "directUrl": "https://tv.youtube.com/watch/abc-world-news?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/abc-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-cbs-1",
    "title": "CBS Evening News",
    "description": "The latest news and analysis from around the world with Norah ODonnell.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "cbs-evening-news",
    "directUrl": "https://tv.youtube.com/watch/cbs-evening-news?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/cbs-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-abc-2",
    "title": "Good Morning America",
    "description": "Start your day with the latest news, weather, and inspiring stories from across America.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "gma-abc",
    "directUrl": "https://tv.youtube.com/watch/gma-abc?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/abc-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-cbs-2",
    "title": "The Late Show with Stephen Colbert",
    "description": "Comedy, politics, and celebrity interviews in this Emmy-winning late-night talk show.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "late-show-cbs",
    "directUrl": "https://tv.youtube.com/watch/late-show-cbs?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/tv-icon.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-nbc-1",
    "title": "NBC Nightly News",
    "description": "The days top stories with comprehensive reporting and analysis from Lester Holt.",
    "type": "show",
    "genre": "news",
    "service": "youtube-tv",
    "serviceContentId": "nbc-nightly-news",
    "directUrl": "https://tv.youtube.com/watch/nbc-nightly-news?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/nbc-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-nbc-2",
    "title": "The Tonight Show Starring Jimmy Fallon",
    "description": "Late-night comedy with celebrity interviews, musical performances, and hilarious sketches.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "tonight-show-nbc",
    "directUrl": "https://tv.youtube.com/watch/tonight-show-nbc?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/nbc-official.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-disney-2",
    "title": "Bluey",
    "description": "Australian animated series about a Blue Heeler puppy and her family living everyday adventures.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "disney-bluey",
    "directUrl": "https://tv.youtube.com/watch/disney-bluey?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/xqHt3vc3iKnnp2yuMP2Y4RAZF1Q.jpg",
    "rating": "TV-Y",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-07T03:05:42.427Z"
  },
  {
    "id": "ytv-comedy-1",
    "title": "South Park",
    "description": "Satirical animated series following four boys in the fictional town of South Park.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "comedy-south-park",
    "directUrl": "https://tv.youtube.com/watch/comedy-south-park?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/dqAKFEjPEu7vWkVBkMdhGu9ifxU.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-bbc-2",
    "title": "Doctor Who",
    "description": "Time-traveling adventures of the Doctor, an alien Time Lord exploring the universe.",
    "type": "show",
    "genre": "sci-fi",
    "service": "youtube-tv",
    "serviceContentId": "bbc-doctor-who",
    "directUrl": "https://tv.youtube.com/watch/bbc-doctor-who?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/2JP6NSmBwxg75uTcIHiv5R8PpPi.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-07T03:05:43.263Z"
  },
  {
    "id": "ytv-amc-1",
    "title": "The Walking Dead",
    "description": "Post-apocalyptic horror series following survivors in a zombie-infested world.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "amc-walking-dead",
    "directUrl": "https://tv.youtube.com/watch/amc-walking-dead?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/ywbacot78IuNhGW4uVZPxxxVTkm.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-07T03:05:42.845Z"
  },
  {
    "id": "ytv-fx-1",
    "title": "American Horror Story",
    "description": "Anthology horror series with different storylines and characters each season.",
    "type": "show",
    "genre": "horror",
    "service": "youtube-tv",
    "serviceContentId": "fx-american-horror-story",
    "directUrl": "https://tv.youtube.com/watch/fx-american-horror-story?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/eGUT7j3n3rn5yGihlCgwUnD70HV.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-tbs-2",
    "title": "The Big Bang Theory",
    "description": "Classic sitcom following a group of brilliant scientists and their hilarious social adventures.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "big-bang-tbs",
    "directUrl": "https://tv.youtube.com/watch/big-bang-tbs?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-cartoon-1",
    "title": "Adventure Time",
    "description": "The magical adventures of Finn the Human and Jake the Dog in the Land of Ooo.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "cartoon-adventure-time",
    "directUrl": "https://tv.youtube.com/watch/cartoon-adventure-time?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/vJn7fEoJZNPCp7xKQKrQ4jcCUOx.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-nick-1",
    "title": "SpongeBob SquarePants",
    "description": "The adventures of SpongeBob and his friends in the underwater city of Bikini Bottom.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "nick-spongebob",
    "directUrl": "https://tv.youtube.com/watch/nick-spongebob?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/oEJGhjhBhLFgP9iB05dZLvHRm4Q.jpg",
    "rating": "TV-Y7",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-trutv-1",
    "title": "Impractical Jokers",
    "description": "Four lifelong friends compete in outrageous hidden-camera challenges.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "trutv-impractical-jokers",
    "directUrl": "https://tv.youtube.com/watch/trutv-impractical-jokers?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/tgwncYaLPoqdxzhHrlDuQdHqkS4.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-cartoon-2",
    "title": "Steven Universe",
    "description": "A young boy with magical powers protects humanity alongside the Crystal Gems.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "cartoon-steven-universe",
    "directUrl": "https://tv.youtube.com/watch/cartoon-steven-universe?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/qkcZqbfvXEenUAwoFi6YTBB3WLO.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-nick-2",
    "title": "The Loud House",
    "description": "Lincoln Loud navigates life with his ten sisters in this animated family comedy.",
    "type": "show",
    "genre": "animation",
    "service": "youtube-tv",
    "serviceContentId": "nick-loud-house",
    "directUrl": "https://tv.youtube.com/watch/nick-loud-house?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/4WKzqLGv98MMYnWy8D8RLAkIeul.jpg",
    "rating": "TV-Y7",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-cmt-1",
    "title": "Nashville",
    "description": "Drama series exploring the personal and professional lives of country music stars.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "cmt-nashville",
    "directUrl": "https://tv.youtube.com/watch/cmt-nashville?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/6zVIFjYYBLyhOmh85o0MrHYZNaB.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-trutv-2",
    "title": "The Carbonaro Effect",
    "description": "Michael Carbonaro performs incredible magic tricks on unsuspecting people in everyday situations.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "trutv-carbonaro-effect",
    "directUrl": "https://tv.youtube.com/watch/trutv-carbonaro-effect?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/am9aBRY0ZuUi2wEEUUySNp7ewjT.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-bbc-1",
    "title": "Planet Earth II",
    "description": "David Attenborough presents stunning wildlife footage from around the globe.",
    "type": "show",
    "genre": "documentary",
    "service": "youtube-tv",
    "serviceContentId": "bbc-planet-earth",
    "directUrl": "https://tv.youtube.com/watch/bbc-planet-earth?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/tUKomxy50suT4MyxjYfOJDkZUq3.jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-tnt-1",
    "title": "NBA on TNT",
    "description": "Live NBA games and highlights with expert analysis from Charles Barkley, Shaquille ONeal, and the Inside the NBA crew.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "nba-tnt",
    "directUrl": "https://tv.youtube.com/watch/nba-tnt?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/sports-icon.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-fs1-2",
    "title": "Skip and Shannon: Undisputed",
    "description": "Sports debate show featuring Skip Bayless and Shannon Sharpe discussing the hottest topics in sports.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "fs1-undisputed",
    "directUrl": "https://tv.youtube.com/watch/fs1-undisputed?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/sports-icon.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-cmt-2",
    "title": "CMT Music Videos",
    "description": "The latest country music videos and artist interviews.",
    "type": "show",
    "genre": "music",
    "service": "youtube-tv",
    "serviceContentId": "cmt-music-videos",
    "directUrl": "https://tv.youtube.com/watch/cmt-music-videos?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/music-icon.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-comedy-2",
    "title": "The Daily Show",
    "description": "Satirical news program offering humorous takes on current events and politics.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "comedy-daily-show",
    "directUrl": "https://tv.youtube.com/watch/comedy-daily-show?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/tv-icon.svg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-tnt-2",
    "title": "The Closer",
    "description": "Crime drama following Deputy Chief Brenda Leigh Johnson as she solves Los Angeles most challenging cases.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "closer-tnt",
    "directUrl": "https://tv.youtube.com/watch/closer-tnt?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/sVE7CYf3ZNZ6OIYq5npbA9VdBfv.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:16:25.363Z",
    "updatedAt": "2025-08-06T04:16:25.363Z"
  },
  {
    "id": "ytv-fs1-1",
    "title": "NFL on Fox",
    "description": "Live NFL games and comprehensive coverage with expert analysis and highlights.",
    "type": "show",
    "genre": "sports",
    "service": "youtube-tv",
    "serviceContentId": "fs1-nfl-live",
    "directUrl": "https://tv.youtube.com/watch/fs1-nfl-live?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/network-logos/fox-official.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 180,
    "isLive": true,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "nf-show-3",
    "title": "House of Cards",
    "description": "Frank Underwood manipulates his way through Washington D.C. politics in this dark political drama.",
    "type": "show",
    "genre": "drama",
    "service": "netflix",
    "serviceContentId": "house-of-cards",
    "directUrl": "https://www.netflix.com/title/70178217",
    "imageUrl": "https://m.media-amazon.com/images/M/MV5BODM1NDMxMTI3OF5BMl5BanBnXkFtZTgwMDkxNTcwNjM@._V1_FMjpg_UX1000_.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": "Award Winners",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-06T05:06:02.886Z"
  },
  {
    "id": "nf-show-1",
    "title": "The Bear",
    "description": "A young chef returns to Chicago to run his deceased brothers Italian beef restaurant, bringing fine dining expertise to a chaotic kitchen.",
    "type": "show",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "the-bear",
    "directUrl": "https://www.netflix.com/title/81476453",
    "imageUrl": "https://image.tmdb.org/t/p/w500/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg",
    "rating": "TV-MA",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": "Streaming Hits",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:49.097Z"
  },
  {
    "id": "paramount-show-1",
    "title": "Yellowstone",
    "description": "The Dutton family fights to protect their Montana ranch from those looking to take their land.",
    "type": "show",
    "genre": "drama",
    "service": "paramount-plus",
    "serviceContentId": "yellowstone",
    "directUrl": "https://www.paramountplus.com/shows/yellowstone/",
    "imageUrl": "https://image.tmdb.org/t/p/w500/s4QRRYc1V2e68Qy9Wel9MI8fhRP.jpg",
    "rating": "TV-MA",
    "year": 2018,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": "Trending Now",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:49.543Z"
  },
  {
    "id": "hbo-show-1",
    "title": "Succession",
    "description": "The Roy family fights for control of their media empire as patriarch Logan Roy considers his succession plan.",
    "type": "show",
    "genre": "drama",
    "service": "hbo-max",
    "serviceContentId": "succession",
    "directUrl": "https://play.hbomax.com/series/urn:hbo:series:GYC_JwQqutJ68uwEAAABd",
    "imageUrl": "https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    "rating": "TV-MA",
    "year": 2018,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": "Award Winners",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:49.984Z"
  },
  {
    "id": "hulu-show-1",
    "title": "The Handmaids Tale",
    "description": "In a totalitarian society, a fertile woman is forced to bear children for the ruling class.",
    "type": "show",
    "genre": "drama",
    "service": "hulu",
    "serviceContentId": "handmaids-tale",
    "directUrl": "https://www.hulu.com/series/the-handmaids-tale-565d8976-9d26-4e63-866c-40f8a137ce5d",
    "imageUrl": "https://image.tmdb.org/t/p/w500/eGUT7j3n3rn5yGihlCgwUnD70HV.jpg",
    "rating": "TV-MA",
    "year": 2017,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": "Award Winners",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:50.426Z"
  },
  {
    "id": "prime-show-1",
    "title": "The Boys",
    "description": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    "type": "show",
    "genre": "action",
    "service": "amazon-prime",
    "serviceContentId": "the-boys",
    "directUrl": "https://www.amazon.com/dp/B07KBQZ8MF",
    "imageUrl": "https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
    "rating": "TV-MA",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": "Streaming Hits",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:50.865Z"
  },
  {
    "id": "apple-show-1",
    "title": "Ted Lasso",
    "description": "An American football coach leads a British soccer team despite having no experience in the sport.",
    "type": "show",
    "genre": "comedy",
    "service": "apple-tv",
    "serviceContentId": "ted-lasso",
    "directUrl": "https://tv.apple.com/show/ted-lasso/umc.cmc.vtoh0mn0xn7t3c643xqonfzy",
    "imageUrl": "https://image.tmdb.org/t/p/w500/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
    "rating": "TV-MA",
    "year": 2020,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": "Award Winners",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:51.307Z"
  },
  {
    "id": "disney-show-1",
    "title": "The Mandalorian",
    "description": "A lone Mandalorian bounty hunter in the outer rim travels with a mysterious alien child.",
    "type": "show",
    "genre": "sci-fi",
    "service": "disney-plus",
    "serviceContentId": "the-mandalorian",
    "directUrl": "https://www.disneyplus.com/series/the-mandalorian/3jLIGMDYINqD",
    "imageUrl": "https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    "rating": "TV-14",
    "year": 2019,
    "artist": null,
    "album": null,
    "duration": 40,
    "isLive": false,
    "category": "Streaming Hits",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:52.094Z"
  },
  {
    "id": "nf-show-2",
    "title": "Wednesday",
    "description": "Wednesday Addams investigates a murder spree while navigating new friendships and foes at Nevermore Academy.",
    "type": "show",
    "genre": "comedy",
    "service": "netflix",
    "serviceContentId": "wednesday",
    "directUrl": "https://www.netflix.com/title/81231974",
    "imageUrl": "https://image.tmdb.org/t/p/w500/kKwy8QiXyQocbDj4haUG0uD1SbF.jpg",
    "rating": "TV-14",
    "year": 2022,
    "artist": null,
    "album": null,
    "duration": 50,
    "isLive": false,
    "category": "Streaming Hits",
    "availability": null,
    "createdAt": "2025-08-06T05:06:02.886Z",
    "updatedAt": "2025-08-07T02:52:52.532Z"
  },
  {
    "id": "ytv-fx-2",
    "title": "Atlanta",
    "description": "Comedy-drama series about two cousins navigating the Atlanta rap scene.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "fx-atlanta",
    "directUrl": "https://tv.youtube.com/watch/fx-atlanta?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    "rating": "TV-MA",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-discovery-1",
    "title": "Deadliest Catch",
    "description": "Follow crab fishermen as they face dangerous conditions in the Bering Sea.",
    "type": "show",
    "genre": "reality",
    "service": "youtube-tv",
    "serviceContentId": "discovery-deadliest-catch",
    "directUrl": "https://tv.youtube.com/watch/discovery-deadliest-catch?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/aqF7wHfA2n89zbBqG6DLuDjrHut.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-mtv-2",
    "title": "Teen Mom",
    "description": "Reality series following young mothers navigating parenthood and relationships.",
    "type": "show",
    "genre": "reality",
    "service": "youtube-tv",
    "serviceContentId": "mtv-teen-mom",
    "directUrl": "https://tv.youtube.com/watch/mtv-teen-mom?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/75pVCsDlbEOYZaRlOqumIS3l8rF.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-mtv-1",
    "title": "Ridiculousness",
    "description": "Rob Dyrdek and guests watch and comment on viral internet videos.",
    "type": "show",
    "genre": "comedy",
    "service": "youtube-tv",
    "serviceContentId": "mtv-ridiculousness",
    "directUrl": "https://tv.youtube.com/watch/mtv-ridiculousness?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/4rJdcHQrE4stnZTEAP0m4gnlVQi.jpg",
    "rating": "TV-14",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 30,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-hallmark-1",
    "title": "When Calls the Heart",
    "description": "Period drama about a young teacher in a small frontier town.",
    "type": "show",
    "genre": "drama",
    "service": "youtube-tv",
    "serviceContentId": "hallmark-when-calls-heart",
    "directUrl": "https://tv.youtube.com/watch/hallmark-when-calls-heart?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/opLuX2DHs2aSN8SxMvfOM5b8IkV.jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-natgeo-1",
    "title": "Cosmos: A Spacetime Odyssey",
    "description": "Neil deGrasse Tyson explores the universe and our place within it.",
    "type": "show",
    "genre": "documentary",
    "service": "youtube-tv",
    "serviceContentId": "natgeo-cosmos",
    "directUrl": "https://tv.youtube.com/watch/natgeo-cosmos?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/5o07ps0QZ0bNoRYxTn9cPdRWlUu.jpg",
    "rating": "TV-PG",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-natgeo-2",
    "title": "Wild Yellowstone",
    "description": "Documentary exploring the wildlife and natural wonders of Yellowstone National Park.",
    "type": "show",
    "genre": "documentary",
    "service": "youtube-tv",
    "serviceContentId": "natgeo-wild-yellowstone",
    "directUrl": "https://tv.youtube.com/watch/natgeo-wild-yellowstone?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "https://image.tmdb.org/t/p/w500/7Z3IraZaAO2MU4uOiSSQUo5QbmK.jpg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 60,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  },
  {
    "id": "ytv-hallmark-2",
    "title": "Christmas Movies",
    "description": "Heartwarming holiday movies and romantic stories perfect for the season.",
    "type": "show",
    "genre": "romance",
    "service": "youtube-tv",
    "serviceContentId": "hallmark-christmas-movies",
    "directUrl": "https://tv.youtube.com/watch/hallmark-christmas-movies?vp=0gEEEgIwAQ%3D%3D",
    "imageUrl": "/src/assets/category-icons/tv-icon.svg",
    "rating": "TV-G",
    "year": 2024,
    "artist": null,
    "album": null,
    "duration": 120,
    "isLive": false,
    "category": null,
    "availability": null,
    "createdAt": "2025-08-06T04:27:34.524Z",
    "updatedAt": "2025-08-06T04:27:34.524Z"
  }
];

export async function seedRealContent() {
  console.log('🌱 Seeding database with real content...');
  
  try {
    // Clear existing content
    await db.delete(content);
    console.log('✅ Cleared existing content');

    // Insert real content
    for (const item of realContent) {
      await db.insert(content).values(item);
    }
    
    console.log(`✅ Seeded ${realContent.length} real content items`);
        console.log('📺 netflix content:', realContent.filter(c => c.service === 'netflix').length);
    console.log('📺 youtube-tv content:', realContent.filter(c => c.service === 'youtube-tv').length);
    console.log('🎬 amazon-prime content:', realContent.filter(c => c.service === 'amazon-prime').length);
    console.log('📰 cnn content:', realContent.filter(c => c.service === 'cnn').length);
    console.log('🏈 espn-plus content:', realContent.filter(c => c.service === 'espn-plus').length);
    console.log('🎭 hulu content:', realContent.filter(c => c.service === 'hulu').length);
    console.log('🎯 hbo-max content:', realContent.filter(c => c.service === 'hbo-max').length);
    console.log('🎯 apple-tv content:', realContent.filter(c => c.service === 'apple-tv').length);
    console.log('🏰 disney-plus content:', realContent.filter(c => c.service === 'disney-plus').length);
    console.log('🎯 paramount-plus content:', realContent.filter(c => c.service === 'paramount-plus').length);
    console.log('🎯 All content synchronized from database');
    console.log('🚀 Seed file auto-updated with current database state');
    
  } catch (error) {
    console.error('❌ Error seeding content:', error);
    throw error;
  }
}

// Auto-run seeding if this file is executed directly  
if (import.meta.url === `file://${process.argv[1]}`) {
  seedRealContent()
    .then(() => {
      console.log('✅ Seeding completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Seeding failed:', error);
      process.exit(1);
    });
}
